#ifndef _MSG_SHIM_
#define _MSG_SHIM_

//
// Message identifiers for the loader.
//
// In the NT build these come from msg.h, generated by mc.exe from msg.mc. We
// have no message compiler, so this provides each ID the loader references as a
// distinct constant. BlFindMessage() maps them to text; for now it can return
// NULL and the loader falls back to printing the numeric code.
//
// IDs are arbitrary but distinct and stable.
//

enum _BL_MESSAGE_ID {
    LOAD_HW_MEM_CLASS = 0x1000,
    LOAD_HW_MEM_ACT,
    LOAD_HW_DISK_CLASS,
    LOAD_HW_DISK_ACT,
    LOAD_HW_FW_CFG_CLASS,
    LOAD_HW_FW_CFG_ACT,
    LOAD_SW_MIS_FILE_CLASS,
    LOAD_SW_BAD_FILE_CLASS,
    LOAD_SW_INT_ERR_CLASS,
    LOAD_SW_INT_ERR_ACT,
    LOAD_SW_FILE_REINST_ACT,
    LOAD_SW_FILE_REST_ACT,

    DIAG_BL_MEMORY_INIT = 0x2000,
    DIAG_BL_IO_INIT,
    DIAG_BL_CONFIG_INIT,
    DIAG_BL_FW_GET_BOOT_DEVICE,
    DIAG_BL_FW_GET_SYSTEM_DEVICE,
    DIAG_BL_FW_OPEN_SYSTEM_DEVICE,
    DIAG_BL_OPEN_BOOT_DEVICE,
    DIAG_BL_FIND_HAL_IMAGE,
    DIAG_BL_LOAD_SYSTEM_IMAGE,
    DIAG_BL_LOAD_HAL_IMAGE,
    DIAG_BL_LOAD_SYSTEM_DLLS,
    DIAG_BL_LOAD_HAL_DLLS,
    DIAG_BL_LOAD_SYSTEM_HIVE,
    DIAG_BL_LOAD_SYSTEM_REGISTRY_HIVE,
    DIAG_BL_ARC_BOOT_DEV_NAME,
    DIAG_BL_SETUP_FOR_NT,
    DIAG_BL_KERNEL_INIT_XFER
};

#endif // _MSG_SHIM_
