#!/usr/bin/env bash
# Probe build: try to compile the REAL ntos.h kernel header chain for _ARM_.
#
# Mounts the nt35 tree so the real read-only headers are visible, builds an
# in-container lowercase header farm (Ctrl-Z/CR stripped) of the real headers,
# and -I's: kernel/inc (new ARM arch headers + nt.h/ntos.h shadows) , the loader
# inc/ (proven real-with-_ARM_ ntdef.h/arc.h/ntimage.h/...) , then the farm.
# Nothing is persisted to the repo except kernel/inc. See CLAUDE.md header method.
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NT35="$(cd ../../.. && pwd)"
IMAGE="${IMAGE:-arc-rpi-build:latest}"
TUS="${*:-probe.c}"

docker run --rm -v "$NT35":/work -w /work/ARM32/arcfw/kernel "$IMAGE" bash -c '
set -e
CROSS=arm-linux-gnueabihf-
# Copy the real headers lowercased (Ctrl-Z/CR stripped). Add _ARM_ to the
# unambiguous all-RISC arch gates (#if/#elif lines OR-ing _MIPS_ && _ALPHA_ &&
# _PPC_) - the "any RISC platform" idiom, where ARM belongs exactly as NT added
# each new arch to those lists. MIPS/Alpha/PPC-exclusive gates are left alone.
RISC_SED="/^[[:space:]]*#(if|elif)/{/_MIPS_/{/_ALPHA_/{/_PPC_/s/\$/ || defined(_ARM_)/}}}"
mkfarm(){ s=$1; d=$2; mkdir -p "$d"; for f in "$s"/*.[Hh]; do [ -e "$f" ]||continue; \
          b=$(basename "$f"|tr A-Z a-z); tr -d "\032\r" < "$f" | sed -E "$RISC_SED" > "$d/$b"; done; }
mkfarm /work/PRIVATE/NTOS/INC   /tmp/farm/priv
mkfarm /work/PUBLIC/SDK/INC     /tmp/farm/pub
mkfarm /work/PUBLIC/SDK/INC/CRT /tmp/farm/crt
mkfarm /work/PRIVATE/NTOS/KE    /tmp/farm/ke
# bugcodes.h is generated by mc.exe from NLS/BUGCODES.MC; reproduce it (the value
# is (Severity<<30)|(Facility<<16)|MessageId, Fatal=0/None=1, Kernel=0).
# Facility is always Kernel(0) and ids are 4-digit hex, so the mc.exe value is
# 0x0000<id> (Fatal) or 0x4000<id> (None, severity bit 30). Emit as strings so no
# hex arithmetic (mawk has no strtonum).
gen_mc(){ src=$1; out=$2; { echo "#ifndef _BUGCODES_"; echo "#define _BUGCODES_";
  tr -d "\r" < "$src" | awk "/^MessageId=/{ sev=\"Fatal\"; nm=\"\"; id=\"\";
         for(i=1;i<=NF;i++){ split(\$i,kv,\"=\");
           if(kv[1]==\"MessageId\"){ v=kv[2]; sub(/^0[xX]/,\"\",v); id=v }
           if(kv[1]==\"Severity\"){ sev=kv[2] }
           if(kv[1]==\"SymbolicName\"){ nm=kv[2] } }
         if(nm!=\"\"){ while(length(id)<4) id=\"0\" id;
           hi=(sev==\"None\")?\"4000\":\"0000\";
           printf \"#define %s ((ULONG)0x%s%sL)\n\", nm, hi, id } }";
  echo "#endif"; } > "$out"; }
gen_mc /work/PRIVATE/NTOS/NLS/BUGCODES.MC /tmp/farm/priv/bugcodes.h
INCS="-Iinc -I/work/ARM32/arcfw/inc -I/tmp/farm/ke -I/tmp/farm/priv -I/tmp/farm/pub -I/tmp/farm/crt"
CFLAGS="-mcpu=cortex-a7 -marm -mfloat-abi=soft -ffreestanding -fno-pic -fshort-wchar \
        -D_ARM_ -DNT_UP -DDBG=0 -DFPO=0 -DDEVL=1 -D_EXCEPTION_DISPOSITION_DEFINED \
        -fno-builtin -fno-stack-protector \
        -include /work/ARM32/arcfw/inc/ntshim.h"
# Compile each TU (stripped of Ctrl-Z/CR so real 1994 NT sources compile).
for tu in '"$TUS"'; do
  tr -d "\032\r" < "$tu" > /tmp/tu.c
  if ${CROSS}gcc $CFLAGS $INCS -fsyntax-only -w /tmp/tu.c 2>/tmp/err; then
    echo "OK   : $tu"
  else
    echo "FAIL : $tu"; head -25 /tmp/err
  fi
done
'
